### ISSUE TITLE
Upgrade wagmi to v0.12.8

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#175]

**Comment by biendeveloper** [comment]
Hi @aahna-ashina why v0.12.8 and not latest version?

**Comment by aahna-ashina** [comment]
> Hi @aahna-ashina why v0.12.8 and not latest version?

@biendeveloper See https://discord.com/channels/690584551239581708/1137397630574538782/1138377491183054858

**Comment by RenanCQueiroz** [comment]
The bounty is still open ? I want to do this.

**Comment by aahna-ashina** [comment]
Closed:  https://github.com/nation3/app/pull/178
