### ISSUE TITLE
Publish the goerli `.env` contract addresses

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#18]
@luisivan we should also publish the goerli `.env` contract addresses

_Originally posted by @gregfromstl in https://github.com/nation3/app/issues/14#issuecomment-1129298314_

**Comment by luisivan** [comment]
They actually are in https://github.com/nation3/app/blob/main/contracts/deployments/goerli.json

It would be nice to maybe get rid of getting the variables from ENV for contract deployments? Given that currently having them as env variables doesn't really give us anything special over just committing `goerli.json`, `mainnet.json`, etc.

Thoughts @0xgallego?

**Comment by xPi2** [comment]
IMO we should revamp the config system to use the manifests found on `contracts/deployments` by default and use only the ENV variable to override.

**Comment by aahna-ashina** [comment]
Replaced by #30
