### ISSUE TITLE
Aragon OSx Governance Plugin

### ISSUE THREAD

**Issue by RenanCQueiroz** [nation3/app#180]
Quite weird that the Dework task is not here on GitHub already, therefore I am creating it.

Task in question: https://app.dework.xyz/nation3?taskId=2e5de0e8-33af-455e-962a-0c47035c8a37.

I will develop it over the next few days.

**Comment by aahna-ashina** [comment]
> Quite weird that the Dework task is not here on GitHub already, therefore I am creating it.

@RenanCQueiroz That Dework task is not related to this GitHub repository.  Maybe you were looking for https://github.com/nation3/nation3-voting
