### ISSUE TITLE
Fix broken Discord invite link on /citizen page

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#182]
https://app.nation3.org/citizen

> ![invite](https://github.com/nation3/app/assets/95955389/5e480b61-ad76-4347-a69d-727c1e5e081c)

> ![discord](https://github.com/nation3/app/assets/95955389/a2022c09-6e63-4392-9147-8ae255f8afc3)

**Comment by yahiamarzouk** [comment]
on it

**Comment by 0xbhagi** [comment]
https://github.com/nation3/app/pull/183
