### ISSUE TITLE
Remove `nationPassportRevokeUnderBalance` from config

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#226]
The `nationPassportRevokeUnderBalance` can be changed in the future, so this value should not be statically stored in a config file.

Refactoring tasks:
- Delete `nationPassportRevokeUnderBalance` from `ui/lib/config.ts` and from `contracts/deployments/*.json`.
- Fetch the value directly from the `PassportIssuer` smart contract instead.

**Comment by TTNguyenDev** [comment]
I love to handle this. Can you assign it to me?

**Comment by ravalkenil** [comment]
I can do this task can you assign it to me?
