### ISSUE TITLE
Add missing variables to Görli

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#37]
Add missing variables to the `/join` page connected to the Görli testnet: `statement` and `termsURI`

### Mainnet
![Screen Shot 2022-06-21 at 2 39 23 PM](https://user-images.githubusercontent.com/95955389/174733753-904933c0-70e2-4a84-9e5a-819a773014be.png)

### Görli
<img width="608" alt="Screen Shot 2022-06-21 at 2 39 34 PM" src="https://user-images.githubusercontent.com/95955389/174733763-4fd1db59-2ddd-4da9-9600-6f077d4f3ca6.png">

#### Görli Claim Passport
<img width="365" alt="Screen Shot 2022-06-21 at 1 33 28 PM" src="https://user-images.githubusercontent.com/95955389/174733933-5e98b713-f465-492c-9f38-5362c773f8ad.png">

**Comment by luisivan** [comment]
Closed by https://github.com/nation3/app/pull/39
