### ISSUE TITLE
Move environment variables from Vercel to code

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#53]
https://app.dework.xyz/nation3/app-2?taskId=307bc999-e381-4919-b569-f2a7465f3dbd

To make it easier for developers, we need to move _public_ environment variables out of Vercel.  Development work involving `process.env.*` is now is slow and difficult because not all developers have access to Vercel, and therefore cannot easily know the value of each variable or add/edit variables.

More context here:  https://discord.com/channels/690584551239581708/963778898389237800/999871593184497765

Remove usage of all `process.env.NEXT_PUBLIC_*` variables except for `NEXT_PUBLIC_CHAIN`:
- [ ] Refactor https://github.com/nation3/app/blob/main/ui/lib/config.ts
- [ ] Delete variables from https://github.com/nation3/app/blob/main/ui/.env.goerli
- [ ] Delete variables from https://github.com/nation3/app/blob/main/ui/.env.mainnet

## Admin Tasks
_After_ the PR for this issue has been merged into `main`:
- [ ] In Vercel, remove all `NEXT_PUBLIC_*` variables except for `NEXT_PUBLIC_CHAIN`

**Comment by gregfromstl** [comment]
We should move this to https://github.com/nation3/shared @aahna-ashina

**Comment by aahna-ashina** [comment]
> We should move this to https://github.com/nation3/shared

@gregfromstl Are the shared components using environment variables?
