### ISSUE TITLE
Handle MetaMask RPC Error on /liquidity page

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#69]
How to reproduce:

1. Go to https://app.nation3.org/liquidity
2. Connect an Ethereum account (press "Sign in") using the Ethereum mainnet
3. Open the JavaScript Console

```javascript
inpage.js:1 MetaMask - RPC Error: execution reverted {code: -32603, message: 'execution reverted', data: {…}}
```

The error seems to occur only when the Ethereum account holds zero `$veNATION`.

Refactor the code so that no error is thrown in the console.

**Comment by ef3n9r98** [comment]
Hey @aahna-ashina , if this issue is still open, I know some devs who'd be interested in working on this. Do you have a budget for it? 

Thanks!
