### ISSUE TITLE
Clarify withdraw all and claim /liquidity

### ISSUE THREAD

**Issue by xPi2** [nation3/app#73]
A couple users reported to me the same UX problem.

When trying to withdraw & claim on https://app.nation3.org/liquidity they got confused by the fact that you can select an amount of tokens to withdraw but if you click ¨withdraw all and claim¨ you are actually withdrawing all your staked tokens.

<img width="480" alt="Screenshot 2022-08-08 at 19 26 31" src="https://user-images.githubusercontent.com/32301192/183487562-a9fe4cc1-6447-4aef-81de-1d1a016202a1.png">

As the contract doesn't implement an option to withdraw a set amount and claim on the same transaction i think the best fix would be to add a tooltip in this button that clarifies that you are about to withdraw ALL your tokens.

<img width="468" alt="Screenshot 2022-08-08 at 19 27 16" src="https://user-images.githubusercontent.com/32301192/183488475-2fa81d87-660b-4e39-8cd9-e1974f3c5df6.png">

**Comment by aahna-ashina** [comment]
@xPi2 I would recommend another UX/UI solution:  When a user types an amount into the amount field, disable the "Withdraw all and claim" button.

**Comment by xPi2** [comment]
> @xPi2 I would recommend another UX/UI solution: When a user types an amount into the amount field, disable the "Withdraw all and claim" button.

On the line of your suggestion, only show / able the "Withdraw all and claim" button when the user select MAX

**Comment by aahna-ashina** [comment]
> On the line of your suggestion, only show / able the "Withdraw all and claim" button when the user select MAX

@xPi2 Yes, and only enable the "Withdraw" button after the user has typed an amount larger than zero in the input field.
