### ISSUE TITLE
Prevent lock expiration date slider from resetting itself

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/app#79]
https://app.dework.xyz/nation3/app-2?taskId=0554bc64-e2b2-4161-90b5-75997aaf3891

A bug causes the "Lock expiration date" slider at https://app.nation3.org/lock to automatically adjust itself to the original date after a few seconds, which is causing trouble for users interacting with the app:

![lock_expiration_date](https://user-images.githubusercontent.com/95955389/184296267-417fc7e7-b2da-4876-a6f8-2cb7b915f2e5.gif)

How to reproduce:
1. Go to https://app.nation3.org/lock
2. Adjust the slider, then wait for ~10 seconds

If you are having trouble reproducing this behavior, it could be that this bug only happens for users that have already locked `$NATION`.  If that's the case, you can obtain some test tokens at https://goerli.balancer.fi/#/trade/ether/0x333A4823466879eeF910A04D473505da62142069

**Comment by tayyabmh** [comment]
So it does not happen to me when I try to leave the "lock" at 1 year for 0 locked $NATION... Now I'm trying to lock in Goerli $NATION tokens but it's not letting me because it says "Wrong Network" so likely need to fix that as an issue as well on Goerli.

Will pull down the code and take a look in a bit.

**Comment by aahna-ashina** [comment]
> So it does not happen to me when I try to leave the "lock" at 1 year for 0 locked $NATION... Now I'm trying to lock in Goerli $NATION tokens but it's not letting me because it says "Wrong Network" so likely need to fix that as an issue as well on Goerli.
> 
> Will pull down the code and take a look in a bit.

@tayyabmh To configure the development server to use Goerli instead of Mainnet, you need to add the Goerli variables:  https://github.com/nation3/app/blob/main/ui/README.md#run-the-ui-locally

```
cp .env.goerli .env.local
```

**Comment by tayyabmh** [comment]
Yes, I figured that out! Opened up PR#84. 

Seems to be something failing, I can look into it. Unless this has already been solved.

**Comment by aahna-ashina** [comment]
#84
